#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 11:33:52 2026

@author: Estudiante
"""
import numpy as np

def rota(theta):
    
    T = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
    
    return T
    
assert(np.allclose(rota(0),np.eye(2)))
assert(np.allclose(rota(np.pi/2),np.array([[0,-1],[1,0]])))
assert(np.allclose(rota(np.pi),np.array([[-1,0],[0,-1]])))


