#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 11:33:52 2026

@author: Estudiante
"""
import numpy as np

def rota(theta):
    
    T = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
    
    return T
    
assert(np.allclose(rota(0),np.eye(2)))
assert(np.allclose(rota(np.pi/2),np.array([[0,-1],[1,0]])))
assert(np.allclose(rota(np.pi),np.array([[-1,0],[0,-1]])))

#%%
def escala(s):
    n = len(s)
    res = np.zeros(n,n)
    
    for i in range(n):
        res[i,i] = s[i]
    
    return res
            
assert(np.allclose(escala([2,3]),np.array([[2,0],[0,3]])))
assert(np.allclose(escala([1,1,1]),np.eye(3)))
assert(np.allclose(escala([0.5,0.25]),np.array([[0.5,0],[0,0.25]])))